config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'conversations/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :conversations do
    resources :messages
  end

  resources :reservations do
    member do
      put 'reject_status'
    end
  end
  resources :tables
  resources :restaurants do
    resources :reviews, only: %i[new create edit update destroy]
    resources :reservations, only: %i[new create edit update destroy]
    resources :tables, only: %i[new create edit update destroy]
  end
  # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/about'
  get 'welcome/index'
  get 'welcome/termsofuse'
  root to: 'welcome#index'
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

# ConversationsController
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/helpers/conversations_helper.rb
# frozen_string_literal: true

# ConversationsHelper
module ConversationsHelper
end

app/views/conversations/index.html.erb
<br><br><br><br><br>
<div align="center">
<h1>Todas mis conversaciones</h1>

<% @conversations.each do |conversation| %>
<div>
  <%= link_to conversation.subject, conversation_path(conversation) %>
</div>
<% end %>

<br>
<%= link_to "Nueva conversación", new_conversation_path, class:"btn-link" %>
</div>
<br><br><br><br><br><br><br><br>

app/views/conversations/new.html.erb
<br><br><br><br>
<div align="center">
<br>
<h1>Nueva conversación</h1><br>

<%= form_tag conversations_path, method: :post do %>
<div>
  <div>
    <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name), class:"form-select-sm" %>
  </div>
   <br>
  <div>
    <%= text_field_tag :subject, nil, placeholder:"Asunto", class:"form-control-sm", required: true %>
  </div>
   <br>
  <div>
    <%= text_area_tag :body, nil, placeholder:"Deja un comentario", class:"form-control-sm", required: true %>
  </div>

<%= submit_tag "Enviar mensaje", class:"btn btn-success" %>
</div>
<% end %>
</div>
<br><br><br><br><br><br><br>

app/views/conversations/show.html.erb
<br><br><br><br><br><br>
<div align="center">
<h1> <%= @conversation.subject %></h1>

<% @conversation.receipts_for(current_user).each do |receipt| %>
  <div>
    <div><%= receipt.message.sender.name %> comentó:</div>
    <p><%= receipt.message.body %></p> 
  </div> 
<% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
<br>
<div>
  <%= text_area_tag :body, nil, placeholder:"Deja un comentario", class:"form-control-sm", required: true %>
</div>

<%= submit_tag "Enviar mensaje", class:"btn btn-success" %>
<% end %>
</div>
<br><br><br><br><br><br>