config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'conversations/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :conversations do
    resources :messages
  end

  resources :reservations do
    member do
      put 'reject_status'
    end
  end
  resources :tables
  resources :restaurants do
    resources :reviews, only: %i[new create edit update destroy]
    resources :reservations, only: %i[new create edit update destroy]
    resources :tables, only: %i[new create edit update destroy]
  end
  # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/about'
  get 'welcome/index'
  get 'welcome/termsofuse'
  root to: 'welcome#index'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
end

app/models/reservation.rb
# frozen_string_literal: true

# Model for reservation
class Reservation < ApplicationRecord
  validates :nombre_usuario, :fecha_reserva, :hora_inicio, :hora_termino, presence: true

  enum status: %i[pendiente aprobada rechazada]
  belongs_to :user
  belongs_to :restaurant

  validate :fecha_reserva_cannot_be_in_the_past
  validate :hora_termino_despues_hora_inicio

  def fecha_reserva_cannot_be_in_the_past
    #errors.add(:fecha_reserva, 'no puede ser anterior al día actual') if fecha_reserva.present? && fecha_reserva < Date.today
    flash[:error] = :fecha_reserva, 'no puede ser anterior al día actual' if fecha_reserva.present? && fecha_reserva < Date.today
  end

  def hora_termino_despues_hora_inicio
    errors.add(:hora_termino, 'debe ser después de la hora de inicio.') if hora_termino <= hora_inicio
  end

  belongs_to :user
  belongs_to :restaurant
  has_one :table, dependent: :nullify
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  validates :name, :address, :commune, :open, :close, :rating, :food, :logo, :description, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 0 }
  attribute :rating, :integer, default: 0
  has_one_attached :logo
  has_many :reviews, dependent: :destroy

  scope :filter_by_commune, ->(commune) { where commune: commune }
  scope :filter_by_food, ->(food) { where food: food }
  scope :filter_by_rating, ->(rating) { where('rating >= ?', rating) }
  has_many :reservations, dependent: :destroy
  has_many :tables, dependent: :destroy
  belongs_to :user
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  validates :title, :body, :rating, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 0 }

  belongs_to :user
  belongs_to :restaurant
end

app/models/table.rb
# frozen_string_literal: true

class Table < ApplicationRecord
  validates :nombre_restaurant, :capacidad, :ubicacion, :disponibilidad, presence: true
  validates :capacidad, numericality: { only_integer: true, greater_than: 0 }
  attribute :disponibilidad, :boolean, default: true

  has_one :reservation
  belongs_to :restaurant
end

app/models/user.rb
# frozen_string_literal: true

# Model for user
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_messageable

  def mailboxer_email(_object)
    nil
  end

  validates :name, presence: true
  enum role: %i[user moderator]
  has_many :reviews, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :restaurants, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Controller for Application
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# MessagesController
class MessagesController < ApplicationController
  before_action :set_conversation

  def create
    receipt = current_user.reply_to_conversation(@conversation, params[:body])
    redirect_to conversation_path(receipt.conversation)
  end

  private

  def set_conversation
    @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

# Controller for Reviews
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurants_path(anchor: 'portfolio')
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.update(review_params)

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :edit

    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:title, :body, :rating)
  end
end

app/controllers/tables_controller.rb
# frozen_string_literal: true

# Controller for tables
class TablesController < ApplicationController
  before_action :authenticate_user!
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @table = Table.new(table_params)
    @table.restaurant = @restaurant
    if @table.save
      redirect_to restaurants_path(anchor: 'portfolio')
    else
      render :new
    end
  end

  def edit
    @table = Table.find(params[:id])
  end

  def update
    @table = Table.find(params[:id])
    @table.update(table_params)

    if @table.save
      redirect_to tables_path
    else
      render :edit

    end
  end

  def destroy
    @table = Table.find(params[:id])
    if !@table.reservation_id.blank?
      @reservation = Reservation.find(@table.reservation_id)
      @reservation.destroy
    end
    @table.destroy
    redirect_to tables_path
  end

  def index
    @tables = Table.all
  end

  private

  def table_params
    params.require(:table).permit(:nombre_restaurant, :capacidad, :ubicacion, :disponibilidad, :fumador)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Controller for Welcome
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index about termsofuse]
  def index
    @disable_nav = true
  end

  def about; end
  def termsofuse; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper for Application
module ApplicationHelper
end

app/helpers/conversations_helper.rb
# frozen_string_literal: true

# ConversationsHelper
module ConversationsHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

# MessagesHelper
module MessagesHelper
end

app/helpers/reservations_helper.rb
# frozen_string_literal: true

# Helper for Reservation
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

# Helper for Restaurant
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

# Helper for Reviews
module ReviewsHelper
end

app/helpers/tables_helper.rb
# frozen_string_literal: true

# Helper for Table
module TablesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Helper for User
module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

# Helper for Welcome
module WelcomeHelper
end

app/views/reviews/edit.html.erb
<br><br><br><br><br>

<%= form_with model: [@restaurant, @review] do |form| %>
<div class="container" align="center">
<h1>Edit Review</h1><br>
    <div>
        <%= form.label :'Title' %>
        <%= form.text_field :'title' %>
    </div>
    <div>
        <%= form.label :Body %>
        <%= form.text_field :body %>
    </div>
    <div>
        <%= form.label :Rating %>
        <%= form.text_field :rating %>
    </div>
    <div>
        <%= form.submit "Edit Review"%>
    </div>
<% end %>
<br>
<%= link_to 'Back', restaurants_path(anchor: 'portfolio') %>
</div>
<br><br><br><br><br><br><br><br>

app/views/reviews/new.html.erb
<br><br><br><br>

<br><br>
<%= form_with model: [@restaurant, Review.new] do |form| %>
<div class="container", align="center">
    <h1>Nueva reseña</h1> <br>
    <div class="field form-group">
        <%= form.text_field :'title', autofocus: true, class:"form-control w-25", autocomplete: "título", placeholder: "Título" %>
    </div>
    <div class="field form-group">
        <%= form.text_field :body, class:"form-control w-25", autocomplete: "email", placeholder: "Comentario" %>
    </div>
    <div class="field form-group">
        <%= form.label :Rating %>
        <%= form.select(:rating, [1,2,3,4,5]) %>
    </div>
    <div class="field form-group">
        <%= form.submit "Create Review", class:"btn btn-success"%>
    </div>
    <%= link_to 'Back', restaurants_path(anchor: 'portfolio'), class:"btn btn-dark" %>
<% end %>
<br>
</div>
<br><br><br><br><br><br>

app/views/tables/edit.html.erb
<br><br><br><br><br>
<div class='container' align='left'>
<h1>Edit Table</h1><br>

<%= form_for @table do |form| %>
<form>
<% if @table.errors.any? %>
    <h2>Errors:</h2>
    <ul><% @table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <div class="form-group row">
    <label for="inputUsername" class="col-sm-2 col-form-label"><%= form.label :'Restaurant_name' %></label>
    <div class="col-sm-10">
      <%= form.text_field :'nombre_restaurant', class:"form-control w-25", placeholder:"Restaurant name" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputTableID" class="col-sm-2 col-form-label"><%= form.label :Capacity %></label>
    <div class="col-sm-10">
      <%= form.text_field :capacidad, class:"form-control w-25", placeholder:"Capacity" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputStartTime" class="col-sm-2 col-form-label"><%= form.label :Location %></label>
    <div class="col-sm-10">
      <%= form.text_field :ubicacion, class:"form-control w-25", placeholder:"Location" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputEndingTime" class="col-sm-2 col-form-label"><%= form.label :Availability %></label>
    <div class="col-sm-10">
      <%= form.text_field :disponibilidad, class:"form-control w-25", placeholder:"Availability" %>
    </div>
  </div>    

  <div class="form-group row">
    <label for="inputEndingTime" class="col-sm-2 col-form-label"><%= form.label :Smoking_area %></label>
    <div class="col-sm-10">
      <%= form.text_field :fumador, class:"form-control w-25", placeholder:"Smoking area" %>
    </div>
  </div> 

    <div>
        <%= form.submit "Save", class:"btn btn-secondary"%>
        <%= link_to 'Back', tables_path, class:"btn btn-dark"%>
    </div>
</form>
<% end %>
</div>
<br><br>

app/views/tables/index.html.erb
<br><br><br><br><br>
<div class="container", align="center">
  <h1>Revisa las mesas!</h1>
</div>

<br>
<table class="table table-striped table-hover w-50", align="center">
  <thead class="thead-dark">
    <tr>
        <th>Restaurante</th>
        <th>Disponibilidad</th>
        <th>Capacidad</th>
        <th>Ubicación</th>
        <th>Área fumadores</th>
        <th></th>
        <% if current_user && current_user.moderator? %>
        <th></th>
        <th></th>
        <% end %>
    </tr>
        <% @tables.each do |table| %>
        <tr>
          <% if current_user.id == table.restaurant.user_id %>
            <td><%= table.restaurant.name%></td>
            <% if table.disponibilidad %>
              <td> Si </td>
            <% else %>
              <td>No</td>
            <% end %>
            <td><%= table.capacidad%></td>
            <td><%= table.ubicacion%></td>
            <% if table.fumador %>
              <td> Si </td>
            <% else %>
              <td>No</td>
            <% end %>
            <% if current_user && current_user.moderator? %>
                <td><%= link_to 'Editar', edit_table_path(table), class:"btn btn-info btn-sm" %></td>
                <td><%= link_to 'Eliminar', table_path(table), class:"btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?'} %></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>

</table>
<% if !Table.any? %>
  <div align="center">
  <h4>No hay ninguna mesa creada aún.</h4>
  </div>
<% end %>
<h4 align= 'center'><%= link_to 'Volver', restaurants_path(anchor: 'portfolio'), class:"btn btn-dark btn-sm" %></h4>
<br><br><br><br><br><br><br>

app/views/tables/new.html.erb
<br><br><br><br>
<br>
<%= form_with model: [@restaurant, Table.new] do |form| %>
<div class="container">
<h1>Nueva mesa</h1><br>
<form><% if Table.new.errors.any? %>
    <h2>Errors:</h2>
    <ul><% Table.new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <div class="form-group row">
    <label for="inputUsername" class="col-sm-2 col-form-label"><%= form.label :'Nombre restaurant' %></label>
    <div class="col-sm-10">
      <%= form.text_field :'nombre_restaurant', class:"form-control w-25", placeholder:"Restaurant name", value: @restaurant.name, readonly: true %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputTableID" class="col-sm-2 col-form-label"><%= form.label :Capacidad %></label>
    <div class="col-sm-10">
      <%= form.select(:capacidad, [1,2,3,4,5,6,7,8]) %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputUbicacion" class="col-sm-2 col-form-label"><%= form.label :Ubicación %></label>
    <div class="col-sm-10">
      <%= form.select(:ubicacion, ["Afuera", "Adentro"]) %>
    </div>
  </div>
 

  <div class="form-group row">
    <label for="inputFumadores" class="col-sm-2 col-form-label"><%= form.label 'Área fumadores' %></label>
    <div class="col-sm-10">
      <%= form.select(:fumador, [["Si", true], ["No", false]]) %>
    </div>
  </div> 

    <div>
        <%= form.submit "Crear mesa", class:"btn btn-secondary" %>
        <%= link_to 'Volver', restaurants_path(anchor: 'portfolio'), class:"btn btn-dark" %>
    </div>
</form>
</div>
<% end %>
<br><br><br><br><br><br>

app/views/welcome/_contact.html.erb
<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Contáctanos</h2>
            <h3 class="section-subheading text-muted">Esta funcionalidad aún no ha sido implementada, estamos trabajando para usted.</h3>
        </div>
        <!-- * * * * * * * * * * * * * * *-->
        <!-- * * SB Forms Contact Form * *-->
        <!-- * * * * * * * * * * * * * * *-->
        <!-- This form is pre-integrated with SB Forms.-->
        <!-- To make this form functional, sign up at-->
        <!-- https://startbootstrap.com/solution/contact-forms-->
        <!-- to get an API token!-->
        <form id="contactForm" data-sb-form-api-token="API_TOKEN">
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <!-- Name input-->
                        <input class="form-control" id="name" type="text" placeholder="Tu Nombre *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="name:required">Un nombre es requerido.</div>
                    </div>
                    <div class="form-group">
                        <!-- Email address input-->
                        <input class="form-control" id="email" type="email" placeholder="Tu Email *" data-sb-validations="required,email" />
                        <div class="invalid-feedback" data-sb-feedback="email:required">Un email es requerido.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email no es válido.</div>
                    </div>
                    <div class="form-group mb-md-0">
                        <!-- Phone number input-->
                        <input class="form-control" id="phone" type="tel" placeholder="Tu Teléfono *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="phone:required">Un número telefónico es requerido.</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        <!-- Message input-->
                        <textarea class="form-control" id="message" placeholder="Tu Mensaje *" data-sb-validations="required"></textarea>
                        <div class="invalid-feedback" data-sb-feedback="message:required">Un mensaje es requerido.</div>
                    </div>
                </div>
            </div>
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
                <div class="text-center text-white mb-3">
                    <div class="fw-bolder">Form submission successful!</div>
                    To activate this form, sign up at
                    <br />
                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
            <!-- Submit Button-->
            <div class="text-center"><button class="btn btn-primary btn-xl text-uppercase disabled" id="submitButton" type="submit">Enviar Mensaje</button></div>
        </form>
    </div>
</section>

app/views/welcome/_footer.html.erb
<footer class="footer py-4">
      <div class="container">
          <div class="row align-items-center">
              <div class="col-lg-4 text-lg-start">Copyright &copy; Reserv-eat 2022</div>
              <div class="col-lg-4 my-3 my-lg-0">
              <%= link_to "https://twitter.com/TheRock" do %>
                    <button class= "btn btn-dark btn-social mx-2" aria-label="Twitter"> <i class="fab fa-twitter"></i> </button>
                <% end%>
                <%= link_to "https://www.youtube.com/watch?v=vr79HA2V27M&ab_channel=DJJoseB" do %>
                    <button class= "btn btn-dark btn-social mx-2" aria-label="Youtube"> <i class="fab fa-youtube"></i> </button>
                <% end%>
                <%= link_to "https://www.linkedin.com/in/dwayne-johnson-05637a103" do %>
                    <button class= "btn btn-dark btn-social mx-2" aria-label="LinkedIn"> <i class="fab fa-linkedin-in"></i> </button>
                <% end%>
                  
              </div>
              <div class="col-lg-4 text-lg-end">
                  <%= link_to "Política de privacidad", "https://www.privacypolicygenerator.info/live.php?token=t07uQ8UZpJjmvtThj05p2LmFS5WVzS2q", class:"link-footer" %>
                  <%= link_to "Términos de uso", 'welcome/termsofuse', class:"link-footer" %>
              </div>
          </div>
      </div>
  </footer>

app/views/welcome/_header.html.erb
<% if @disable_nav %>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id=mainNav>
<% else %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id=mainNav>
<% end %>
<div class="container">
<% if @disable_nav %>
  <a class="navbar-brand" href="#page-top"><img src="../assets/reserv-eat-logo.png" alt="..." /></a>
  <% else %>
  <%= link_to root_path do %>
    <%= image_tag "/assets/reserv-eat-logo.png", height: 27 %>
<% end%>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    Menu
                <i class="fas fa-bars ms-1"></i>
            </button>

  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
    <li class="nav-item">
      <%= link_to "Restaurantes", restaurants_path(anchor: 'portfolio'), :class => 'nav-link'  %>
    </li>
    <% if current_user && current_user.moderator? %>
    <li class="nav-item">
      <%= link_to "Reservas", reservations_path, class:"nav-link" %>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to "Mis reservas", reservations_path, class:"nav-link" %>
    </li>
    <% end %>
    <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "Mis mensajes", conversations_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to "Mis mensajes", conversations_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Crear cuenta", new_user_registration_path, :class => 'nav-link'  %>
    </li>
    <li class="nav-item">
      <%= link_to "Iniciar sesión", new_user_session_path, :class => 'nav-link'  %>
    </li>
    
    <% end %>
    
    </ul>
  </div>
</div>
</nav>

app/views/welcome/about.html.erb
<h1>hola</h1>

app/views/welcome/index.html.erb
<body id="page-top">
  <!-- Masthead-->
  <header class="masthead">
      <div class="container">
          <div class="masthead-subheading">Bienvenido a Reserv-eat!</div>
          <div class="masthead-heading text-uppercase">Es un placer conocerte</div>
          <a class="btn btn-primary btn-xl text-uppercase" href="#services">¿Cómo funciona?</a>
      </div>
  </header>
  <!-- Services-->
  <section class="page-section" id="services">
      <div class="container">
          <div class="text-center">
              <h3 class="section-heading text-uppercase">Te ofrecemos lo mejor de lo mejor</h3>
              <h3 class="section-subheading text-muted">¿Lo quieres? ¡Reserv-eat!</h3>
          </div>
          <div class="row text-center">
              <div class="col-md-4">
                  <span class="fa-stack fa-4x">
                      <i class="fas fa-circle fa-stack-2x text-primary"></i>
                      <i class="fas fa-book-open fa-stack-1x "></i>
                  </span>
                  <h4 class="my-3">Explora</h4>
                  <p class="text-muted">En Reserv-eat, tenemos cientos de restaurantes disponibles para ti. Mira las opciones y escoge la que más te gusta!</p>
              </div>
              <div class="col-md-4">
                  <span class="fa-stack fa-4x">
                      <i class="fas fa-circle fa-stack-2x text-primary"></i>
                      <i class="fas fa-address-book fa-stack-1x "></i>
                  </span>
                  <h4 class="my-3">Reserva</h4>
                  <p class="text-muted">Reservar una mesa en tu restaurant favorito jamás ha sido más fácil! Solamente ingresa tus datos y envía tu solicitud de reserva.</p>
              </div>
              <div class="col-md-4">
                  <span class="fa-stack fa-4x">
                      <i class="fas fa-circle fa-stack-2x text-primary"></i>
                      <i class="fas fa-glass-cheers fa-stack-1x "></i>
                  </span>
                  <h4 class="my-3">Disfruta</h4>
                  <p class="text-muted">Una vez que tu solicitud haya sido aceptada, recibirás un mail con la confirmación e información de tu reserva. Ahora solo basta que disfrutes de tu gran jornada!</p>
              </div>
          </div>
      </div>
  </section>
<div class="container", align="center">
</div>
  <!-- Team-->
  <section class="page-section bg-light" id="team">
      <div class="container">
          <div class="text-center">
              <h2 class="section-heading text-uppercase">Nuestro increíble equipo</h2>
              <h3 class="section-subheading text-muted">Lleno de talento y simpatía</h3>
          </div>
          <div class="row">
              <div class="col-lg-4">
                  <div class="team-member">
                      <img class="mx-auto rounded-circle" src="../assets/team/paisaje1.jpg" alt="..." />
                      <h4>Julián Araya</h4>
                      <p class="text-muted">Cofundador</p>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                  </div>
              </div>
              <div class="col-lg-4">
                  <div class="team-member">
                      <img class="mx-auto rounded-circle" src="../assets/team/paisaje7.jpg" alt="..." />
                      <h4>Fabiola Garuti</h4>
                      <p class="text-muted">Cofundadora</p>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Twitter Profile"><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                  </div>
              </div>
              <div class="col-lg-4">
                  <div class="team-member">
                      <img class="mx-auto rounded-circle" src="../assets/team/paisaje2.jpg" alt="..." />
                      <h4>Juan Fernández</h4>
                      <p class="text-muted">Cofundador</p>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Twitter Profile"><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                  </div>
              </div>
          </div>
          <div class="row">
              <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">Por muy alta que sea una montaña, siempre hay un camino hacia la cima.</p></div>
          </div>
      </div>
  </section>
  <!-- Contact-->
  <%= render 'welcome/contact' %>
  <!-- Portfolio Modals-->
  <!-- Portfolio item 1 modal popup-->
  <!-- Portfolio item 2 modal popup-->
</body>