config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'conversations/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :conversations do
    resources :messages
  end

  resources :reservations do
    member do
      put 'reject_status'
    end
  end
  resources :tables
  resources :restaurants do
    resources :reviews, only: %i[new create edit update destroy]
    resources :reservations, only: %i[new create edit update destroy]
    resources :tables, only: %i[new create edit update destroy]
  end
  # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/about'
  get 'welcome/index'
  get 'welcome/termsofuse'
  root to: 'welcome#index'
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  validates :name, :address, :commune, :open, :close, :rating, :food, :logo, :description, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 0 }
  attribute :rating, :integer, default: 0
  has_one_attached :logo
  has_many :reviews, dependent: :destroy

  scope :filter_by_commune, ->(commune) { where commune: commune }
  scope :filter_by_food, ->(food) { where food: food }
  scope :filter_by_rating, ->(rating) { where('rating >= ?', rating) }
  has_many :reservations, dependent: :destroy
  has_many :tables, dependent: :destroy
  belongs_to :user
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

# Controller for Restaurant
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  def index
    @restaurants = Restaurant.all

    @restaurants = @restaurants.filter_by_commune(params[:commune]) if params[:commune].present?
    @restaurants = @restaurants.filter_by_food(params[:food]) if params[:food].present?
    @restaurants = @restaurants.filter_by_rating(params[:rating]) if params[:rating].present?
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.save
      redirect_to restaurants_path(anchor: 'portfolio')
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    @restaurant.update(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path(anchor: 'portfolio')
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path(anchor: 'portfolio')
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :commune, :open, :close, :rating, :food, :logo, :slogan, :description)
  end
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

# Helper for Restaurant
module RestaurantsHelper
end

app/views/restaurants/edit.html.erb
<br><br><br><br><br>
<%= form_for @restaurant do |form| %>

<form>
<div class="container">
<h1>Editar restaurante</h1><br>
<% if @restaurant.errors.any? %>
    <h2>Errors:</h2>
    <ul><% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label"><%= form.label "Nombre restaurante" %></label>
    <div class="col-sm-10">
      <%= form.text_field :name, class:"form-control w-25", placeholder:"Nombre" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputSlogan" class="col-sm-2 col-form-label"><%= form.label 'Slogan (opcional)' %></label>
    <div class="col-sm-10">
      <%= form.text_area :slogan, class:"form-control w-25", rows:"2", placeholder:"Slogan" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputAddress" class="col-sm-2 col-form-label"><%= form.label "Dirección" %></label>
    <div class="col-sm-10">
      <%= form.text_field :address, class:"form-control w-25", placeholder:"Dirección" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputCommune" class="col-sm-2 col-form-label"><%= form.label :comuna %></label>
    <div class="col-sm-10">
      <%= form.text_field :commune, class:"form-control w-25", placeholder:"Comuna" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputOpen" class="col-sm-2 col-form-label"><%= form.label "Hora de apertura" %></label>
    <div class="col-sm-10">
      <%= form.time_select :open, {minute_step: 15 , placeholder:"Hora apertura"}, class: "form-control-sm", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputClose" class="col-sm-2 col-form-label"><%= form.label "Hora de cierre" %></label>
    <div class="col-sm-10">
      <%= form.time_select :close, {minute_step: 15 , placeholder:"Hora cierre"}, class: "form-control-sm", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputFood" class="col-sm-2 col-form-label"><%= form.label "Especialidad comida" %></label>
    <div class="col-sm-10">
      <%= form.text_field :food, class:"form-control w-25", placeholder:"Comida" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputDescription" class="col-sm-2 col-form-label"><%= form.label "Descripción" %></label>
    <div class="col-sm-10">
      <%= form.text_area :description, class:"form-control w-25", rows:"3", placeholder:"Descripción" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputLogo" class="col-sm-2 col-form-label"><%= form.label :foto %></label>
    <div class="col-sm-10">
      <%= form.file_field :logo, class:"form-control w-50", placeholder:"Sube una foto de tu restaurant!" %>
    </div>
  </div>

    <div>
        <%= form.submit "Guardar", class:"btn btn-success" %>
        <%= link_to 'Volver', restaurants_path(anchor: 'portfolio'), class:"btn btn-dark" %>
    </div>

</div>
</form>

<% end %>
<br>

app/views/restaurants/index.html.erb
<body id="page-top">
  <!-- Masthead-->
  <header class="masthead1">
      <div class="container">
          <div class="masthead-subheading">Tenemos una gran variedad de restaurantes para ti!</div>
          <div class="masthead-heading text-uppercase">DIVIÉRTETE!</div>
          <a class="btn btn-primary btn-xl text-uppercase" href="#portfolio">EXPLORA</a>
      </div>
  </header><div class="container", align="center">
</div>

<section class="page-section bg-light" id="portfolio">
  <div class="container" align="center">
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <br>
  </div>
      <div class="container">
      
          <div class="row justify-content-evenly">
            <div class="col-lg-4 col-sm-6 mb-4">
              <h2 class="section-heading text-uppercase">Restaurantes</h2>
              <h3 class="section-subheading text-muted">Escoge tu favorito!</h3>
            </div>
            <div class="col-lg-4 col-sm-6 mb-4">
              <%= form_tag(restaurants_path(anchor: 'portfolio'), method: "get") do %>
                <div class="input-group">
                  <div>
                    <%= select_tag :commune, options_for_select(Restaurant.all.collect{ |a| [a.commune, a.commune] }.uniq), class:"form-select ", include_blank: "Todo"%>
                  </div>
              
                  <div>
                    <%= select_tag :food, options_for_select(Restaurant.all.collect{ |a| [a.food, a.food] }.uniq), class:"form-select ", include_blank: "Todo"%>
                  </div>
                
                  <div>
                    <%= select_tag :rating, options_for_select([[1,1], [2,2], [3,3], [4,4], [5,5]]), class:"form-select ", include_blank: "Todo"%>
                  </div>
                  
                  <div>
                  <%= submit_tag "Filtrar", class: "btn btn-dark" %>
                  </div>
                </div>
                <% end %>
            </div>
          </div>

          <div class="row">
          <% @restaurants.each do |restaurant| %>
              <div class="col-lg-4 col-sm-6 mb-4">
                  <!-- Portfolio item 1-->
                  <div class="portfolio-item">
                      <a class="portfolio-link" data-bs-toggle="modal" href="#restaurant_<%= restaurant.id %>">
                          <div class="portfolio-hover">
                              <div class="portfolio-hover-content"><i class="far fa-eye fa-3x"></i></div>
                          </div>
                          <img class="img-fluid rounded" src="<%=(url_for(restaurant.logo)) %>" alt="No hay foto disponible" />
                      </a>
                      <div class="portfolio-caption">
                          <div class="portfolio-caption-heading"><%= restaurant.name %></div>
                          <div class="portfolio-caption-subheading text-muted"><%= restaurant.food %></div>
                      </div>
                  </div>
              </div>
              <% end %>
          </div>
      </div>
  </section>

<% @restaurants.each do |restaurant| %>
<% if !restaurant.reviews.blank? %>
  <% restaurant.update(rating: restaurant.reviews.average(:rating).round) %>
<% end %>
<div class="portfolio-modal modal fade" id="restaurant_<%= restaurant.id %>" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="close-modal" data-bs-dismiss="modal"><img src="/assets/close-icon.svg" alt="Close modal" /></div>
              <div class="container">
                  <div class="row justify-content-evenly">
                      <div class="col-lg-4">
                          <div class="modal-body">
                              <!-- Project details-->
                              <h2 class="text-uppercase"><%= restaurant.name %></h2>
                              <p class="item-intro text-muted"><%= restaurant.slogan %></p>
                              <img class="img-fluid d-block mx-auto" src="<%=(url_for(restaurant.logo)) %>" alt="..." />
                              <p align="left"><%= restaurant.description %></p>
                          </div>
                      </div> 
                      <div class="col-lg-4">
                          <div class="modal-body">
                              <ul class="list-inline-details" align="left">
                                  <li>
                                      <strong>Dirección:</strong>
                                      <%= restaurant.address %>
                                  </li>
                                  <li>
                                      <strong>Comuna:</strong>
                                      <%= restaurant.commune %>
                                  </li>
                                  <li>
                                      <strong>Hora de apertura:</strong>
                                      <%= restaurant.open.strftime("%I:%M%p") %>
                                  </li>
                                  <li>
                                      <strong>Hora de cierre:</strong>
                                      <%= restaurant.close.strftime("%I:%M%p") %>
                                  </li>
                                  <li>
                                      <strong>Especialidad :</strong>
                                      <%= restaurant.food %>
                                  </li>
                                  <li>
                                      <strong>Reseñas :</strong>
                                      <% if restaurant.reviews.blank? %>
                                        No reviews yet
                                      <% else %>
                                      <td><% restaurant.rating.times do %>
                                  <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                          </svg></span>
                                      <% end %>
                                  <% ( 5 - restaurant.rating).times  do %>
                                  <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                          </svg></span>
                                  <% end %></td>
                                  <% end %>
                                  </li>
                                  <br>
                          
                              <% if current_user && current_user.moderator? %>
                              <li>
                              <%= link_to new_restaurant_reservation_path(restaurant, @reservation), class:"btn btn-primary btn-xl text-uppercase disabled" do %>
                              <i class="fas fa-address-book me-1"></i> Agendar una reserva <% end %>
                              </li>
                              <% else %>
                              <li>
                              <%= link_to new_restaurant_reservation_path(restaurant, @reservation), class:"btn btn-primary btn-xl text-uppercase" do %>
                              <i class="fas fa-address-book me-1"></i> Agendar una reserva <% end %>
                              </li>
                              <% end %>
                              <br>
                              
                              <% if current_user && current_user.moderator? && current_user.id == restaurant.user_id %>
                                <div>  
                                  <%= link_to "Agregar mesa", new_restaurant_table_path(restaurant, @table), class:"btn btn-info font-weight-bold" %>
                                  <%= link_to "Ver mesas", tables_path, class:"btn btn-info font-weight-bold" %>
                                </div>
                                <br>
                                <div>
                                  <%= link_to 'Editar', edit_restaurant_path(restaurant), class:"btn btn-success" %>
                                  <%= link_to 'Eliminar', restaurant_path(restaurant), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?'} %>                               
                                </div>
                              <% end %>
                                </div>
                              </ul>
                          </div>
                      </div> 
                      <div>
                        <h3>Reseñas</h3>
                        <% if restaurant.reviews.blank? %>
                          <h4>No hay ninguna reseña aún.</h4>
                        <% end %>
                        <% if not (current_user && current_user.moderator?) %>
                          <%= link_to 'Nueva reseña', new_restaurant_review_path(restaurant), class:"btn btn-info" %>
                          <br>
                        <% end %>
                      
                      </div>
                  </div>
                  <div class="row justify-content-evenly">
                  <% restaurant.reviews.each do |review| %>
                    <div class="card cards card-2 text-center" style="width: 22rem;">
                      <div class="card-body">
                      <% if review.rating >= 4 %>
                        <h5 class="card-title"><%= review.title %> <span class="badge badge-success"><%= review.rating %></span></h5>
                      <% elsif review.rating >= 3 %>
                        <h5 class="card-title"><%= review.title %> <span class="badge badge-warning"><%= review.rating %></span></h5>
                      <% else %>
                        <h5 class="card-title"><%= review.title %> <span class="badge badge-danger"><%= review.rating %></span></h5>
                      <% end %>
                        <h6 class="card-subtitle mb-2 text-muted"><%= time_ago_in_words(review.created_at).capitalize %> ago, <%= User.find(review.user_id).name %> said:</h6>
                        <p class="card-text"><%= review.body %></p>
                        <% if user_signed_in? && current_user.id == review.user_id %>
                            <%= link_to 'Editar', edit_restaurant_review_path(restaurant, review), class:"btn btn-secondary btn-sm" %>
                            <%= link_to 'Eliminar', restaurant_review_path(restaurant, review), class:"btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
                        <% end %>
                      </div>
                    </div>
                    <% end %>
                  </div>

              </div>
          </div>
      </div>
      
  </div>
<% end %>

<br>
<div class="container">
<% if user_signed_in? && current_user.moderator? %>
  <h3 align= 'center'><%= link_to 'Nuevo restaurante', new_restaurant_path, class:"btn btn-primary btn-lg" %></h3>
<% end %>
</div>
<br><br>
<%= render 'welcome/contact' %>

app/views/restaurants/new.html.erb
<br><br><br><br><br>
<%= form_for @restaurant do |form| %>

<form>
<div class="container">
<h1>Nuevo restaurante</h1> <br>
<% if @restaurant.errors.any? %>
    <h2>Errors:</h2>
    <ul><% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label"><%= form.label :nombre %></label>
    <div class="col-sm-10">
      <%= form.text_field :name, class:"form-control w-25", placeholder:"Nombre restaurante" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputSlogan" class="col-sm-2 col-form-label"><%= form.label 'Slogan (opcional)' %></label>
    <div class="col-sm-10">
      <%= form.text_field :slogan, class:"form-control w-25", placeholder:"Slogan" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputAddress" class="col-sm-2 col-form-label"><%= form.label "Dirección" %></label>
    <div class="col-sm-10">
      <%= form.text_field :address, class:"form-control w-25", placeholder:"Dirección" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputCommune" class="col-sm-2 col-form-label"><%= form.label :comuna %></label>
    <div class="col-sm-10">
      <%= form.text_field :commune, class:"form-control w-25", placeholder:"Comuna" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputOpen" class="col-sm-2 col-form-label"><%= form.label "Hora de apertura" %></label>
    <div class="col-sm-10">
      <%= form.time_select :open, {minute_step: 15 , placeholder:"Hora apertura"}, class: "form-control-sm", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputClose" class="col-sm-2 col-form-label"><%= form.label "Hora de cierre" %></label>
    <div class="col-sm-10">
      <%= form.time_select :close, {minute_step: 15 , placeholder:"Hora cierre"}, class: "form-control-sm", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputFood" class="col-sm-2 col-form-label"><%= form.label "Especialidad comida" %></label>
    <div class="col-sm-10">
      <%= form.text_field :food, class:"form-control w-25", placeholder:"Comida" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputDescription" class="col-sm-2 col-form-label"><%= form.label "Descripción" %></label>
    <div class="col-sm-10">
      <%= form.text_area :description, class:"form-control w-25", rows:"3", placeholder:"Descripción" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputLogo" class="col-sm-2 col-form-label"><%= form.label :foto %></label>
    <div class="col-sm-10">
      <%= form.file_field :logo, class:"form-control w-50", placeholder:"Sube una foto de tu restauruant" %>
    </div>
  </div>

    <div>
        <%= form.submit "Crear restaurant", class:"btn btn-success"%>
        <%= link_to 'Volver', restaurants_path(anchor: 'portfolio'), class:"btn btn-dark" %>
    </div>
</div>
</form>
<% end %>

app/views/restaurants/show.html.erb
<div>
  <% if @restaurant.logo.attached? %>
    <img src = "<%=(url_for(@restaurant.logo)) %>", class="rounded float-right" alt="<%= 'None' %>">
  <% end %>
</div>
<div class="container">
<br>
<h1><%= @restaurant.name %></h1>
</div>
<% if !@restaurant.reviews.blank? %>
  <% @restaurant.update(rating: @restaurant.reviews.average(:rating).round) %>
<% end %>
<div class = "container">
<%= form_with model: @restaurant do |form| %>    
    <div>
        <%= form.label :address, 'Address: ' %>
        <%= @restaurant.address %>
    </div>
    <div>
        <%= form.label :commune, 'Commune: ' %>
        <%= @restaurant.commune %>
    </div>
    <div>
        <%= form.label :open, 'Opening time: ' %>
        <%= @restaurant.open.strftime("%I:%M%p") %>
    </div>
    <div>
        <%= form.label :close, 'Closing time: ' %>
        <%= @restaurant.close.strftime("%I:%M%p") %>
    </div>
    <div>
        <%= form.label :food, 'Our specialty: '%>
        <%= @restaurant.food %>
    </div>
    <div>
        <%= form.label :rating, 'Rating: '%>
        <% if @restaurant.reviews.blank? %>
              <td><span> No reviews yet</span></td>
            <% else %>
        <% @restaurant.rating.times do %>
        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
</svg></span>
        <% end %>
        <% ( 5 - @restaurant.rating).times  do %>
        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
  <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
</svg></span>
        <% end %>
        <% end %>
        
    </div>

    <div>
        <% if current_user && current_user.moderator? %>
        <%= link_to "Add Tables", new_restaurant_table_path(@restaurant, @table), class:"btn btn-info font-weight-bold" %>
        <%= link_to 'Edit', edit_restaurant_path(@restaurant), class:"btn btn-secondary" %>
        <%= link_to 'Delete', restaurant_path(@restaurant), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?'} %>
        <% end %>
        <%= link_to 'Back', restaurants_path, class:"btn btn-dark" %>
    </div>

    <div>
        <%= link_to "Book a Reservation", new_restaurant_reservation_path(@restaurant, @reservation), class:"btn btn-info font-weight-bold" %>
        <%= link_to "See Tables", tables_path, class:"btn btn-info font-weight-bold" %>
    </div>

    <div>
    <% if current_user && current_user.moderator? %>
    <% end %>
    </div>

    <% end %>
<br>
</table>
<div align='center'>
    <h3>Reviews</h3>
    <% if @restaurant.reviews.blank? %>
      <h4>No reviews just yet, would you like to add the first?</h4>
    <% end %>
    <% if current_user %>
        <%= link_to 'New Review', new_restaurant_review_path(@restaurant), class:"btn btn-info" %>
        <br>
    <% end %>

    <% @restaurant.reviews.each do |review| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
      <% if review.rating >= 4 %>
        <h5 class="card-title"><%= review.title %> <span class="badge badge-success"><%= review.rating %></span></h5>
      <% elsif review.rating >= 3 %>
        <h5 class="card-title"><%= review.title %> <span class="badge badge-warning"><%= review.rating %></span></h5>
      <% else %>
        <h5 class="card-title"><%= review.title %> <span class="badge badge-danger"><%= review.rating %></span></h5>
      <% end %>
        <h6 class="card-subtitle mb-2 text-muted"><%= time_ago_in_words(review.created_at).capitalize %> ago, <%= User.find(review.user_id).name %> said:</h6>
        <p class="card-text"><%= review.body %></p>
        <% if user_signed_in? && current_user.id == review.user_id %>
            <%= link_to 'Edit', edit_restaurant_review_path(@restaurant, review), class:"btn btn-secondary btn-sm" %>
            <%= link_to 'Delete', restaurant_review_path(@restaurant, review), class:"btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
    <% end %>

</div>